"""add browser tracking fields

Revision ID: 9f5e81e101c9
Revises: 32ed0100e367
Create Date: 2026-07-31 19:19:45.383433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f5e81e101c9'
down_revision: Union[str, Sequence[str], None] = '32ed0100e367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_records', sa.Column('platform_video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('video_records', sa.Column('duration_seconds', sa.BigInteger(), nullable=True))
    op.alter_column('video_records', 'progress_seconds',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_index('ix_video_records_last_watched_at', 'video_records', ['last_watched_at'], unique=False)
    op.create_unique_constraint('uq_video_platform_video_id', 'video_records', ['platform', 'platform_video_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_video_platform_video_id', 'video_records', type_='unique')
    op.drop_index('ix_video_records_last_watched_at', table_name='video_records')
    op.alter_column('video_records', 'progress_seconds',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('video_records', 'duration_seconds')
    op.drop_column('video_records', 'platform_video_id')
    # ### end Alembic commands ###
